### PR TITLE
[BassClarinetTest FIX] Javac requires the filename to match the class name

### PR DESCRIPTION
**Pull request by Farenjihn**
Sorry about that, wasn't paying attention.

### CODE REVIEW

**Comment by wasadigi** [comment]
The commit that fixes the classname was actually already in the previous PR, already merged.

**Comment by Farenjihn** [comment]
This commit does not fix the classname but the filename so it matches the classname. Otherwise javac will throw a warning/error.

**Comment by wasadigi** [comment]
Got it: when I looked at the file in the commit, I only saw the removed line and did not pay attention to the file renaming. Thanks!

**Comment by Farenjihn** [comment]
No worries, you've got a lot to proofread!

Thanks.

**Pull request merged**
