### PR TITLE
Add specs for BassGuitar

### PR DESCRIPTION
**Pull request by Gallouche**

### CODE REVIEW

**Comment by wasadigi** [comment]
Thank you!

**Comment by Gallouche** [comment]
ok I will correct ! And yes this is a bass line well known in Jazz where the bass seems to walk 👍 Did i need to change it too ?

**Comment by Gallouche** [comment]
I have chang the fuction sound to play, and i pushed it, what did i need to do next ? pull request again ?

**Comment by wasadigi** [comment]
When I look at the code, I still see String sound = bassGuitar.sound(); Did you push your code?

**Comment by wasadigi** [comment]
Reopen

**Pull request merged**
